### ISSUE TITLE
Installation process 

### ISSUE THREAD

**Issue by Saurabh-704** [cybertec-postgresql/db_migrator#1]
Hello Everyone!
Can someone please help me with the installation process as I am unable to follow the process which is given in Set-up page.
I want to install  this db_migrator extension for psql and my environment is Linux
Thanks in advance.

**Comment by Saurabh-704** [comment]
I have followed this step -
pg_config --sharedir

Output -
<img width="268" alt="db" src="https://user-images.githubusercontent.com/47383623/89374351-c0a57300-d708-11ea-8c65-1c3f890af5b6.png">
And when i am cloning that repository file in that share folder i am getting this issue-
<img width="518" alt="db2" src="https://user-images.githubusercontent.com/47383623/89374402-e6cb1300-d708-11ea-9220-5f5b4fb0502b.png">
Can someone please help me with this?
Thanks in advance!

**Comment by laurenz** [comment]
It would be

    git clone git@github.com:cybertec-postgresql/db_migrator.git

Note that there is a colon (`:`) rather than a slash (`/`) after `github.com`.

You should not clone the repository in `/usr/pgsql-12/share`, but somewhere else like your home directory or `/tmp`.
All you have to make sure is that `/usr/pgsql-12/bin` is on your `PATH`, so that `pg_config` is on it. That already seems to be the case.

**Comment by Saurabh-704** [comment]
Thank you @laurenz . I was able to install successfully.
