### ISSUE TITLE
Why db_migrator is relocatable?

### ISSUE THREAD

**Issue by fljdin** [cybertec-postgresql/db_migrator#31]
I was wandering how refactor those lines in many place of `db_migrator` where `extschema` is set with a `pg_extension` search:

```sql
EXECUTE format('SET LOCAL search_path = %I, %s', pgstage_schema, extschema);
```

After reading [documentation] about extension's relocatability, is there any reason to relocate `db_migrator` in a database? As functions are calling each others, it might be acceptable to forbid `ALTER EXTENSION SET SCHEMA` and use `@extschema@` wildcard to refer to the extension schema, set during installation only.

[documentation]: https://www.postgresql.org/docs/current/extend-extensions.html#EXTEND-EXTENSIONS-RELOCATION

Regards, Florent

**Comment by laurenz** [comment]
I have no strong opinion on that. I guess I made the extension relocatable since I thought "why not".

But your consideration has merit. There is no real need to relocate the extension (you can simply drop and re-create it), and if it simplifies the code, I have nothing against that change.

Feel free to make that change!
